#!/hint/bash

#
# copy to /etc/xdg/pacaur/config to configure pacaur system-wide or to
# ~/.config/pacaur/config to configure it for your user
#

# The following options are commented out with their default values listed.
# If you wish to use different values, uncomment and update the values.
# The Color and VerbosePkgLists options can be enabled in /etc/pacman.conf.
# The clone directory can be changed through the $AURDEST environment variable.
# The makepkg environment variables are also fully honored.
#editor="${VISUAL:-${EDITOR:-vi}}"     # build files editor
#displaybuildfiles=diff                # display build files (none|diff|full)
#silent=false                          # silence output
#sortby=name                           # sort method (name|votes|popularity)
#sortorder=ascending                   # sort order (ascending|descending)
#sudoloop=true                         # prevent sudo timeout

# vim:set ts=4 sw=4 et:
